<?php

return [
    'name' => 'AppSetting',
    'icon' => 'fas fa-cogs',
    'basic' => [
        'facebook' => env('FACEBOOK', ''),
        'name' => env('APP_NAME', 'BNF Express'),
        'email' => env('APP_EMAIL', 'bnfexpress@gmail.com'),
        'address' => env('APP_ADDRESS', 'No. 391 Waizayantar Road, Za/South Quarter, Thingangyun Township, Yangon, Myanmar.'),
        'phone' => env('APP_PHONE', ''),
        'main_logo' => env('MAIN_LOGO', ''),
        'favicon' => env('APP_FAVICON', ''),
        'map_key' => env('GOOGLE_MAP', ''),
        'meta_keywords' => env('META_KEYWORDS'),
        'meta_description' => env('META_DESCRIPTION'),
    ],
    'payment' => [
        // 'minimum_topup_amount' => env('MINIMUM_TOPUP_AMOUNT'),
        // 'currency_exchange' => env('CURRENCY_EXCHANGE'),
        // 'expired_minute' => env('EXPIRED_MINUTE'),
        'paypal' => [
            'enable' => env('PAYPAL_ENABLE', ''),
            'payment_url' => env('PAYPAL_PAYMENT_URL', ''),
            'email' => env('PAYPAL_EMAIL', ''),
            'charge_type' => env('PAYPAL_CHARGE_TYPE', ''),
            'charge' => env('PAYPAL_CHARGE', ''),
        ],
        'mpu' => [
            'enable' => env('MPU_ENABLE', ''),
            'version' => env('MPU_VERSION', '6.9'),
            'hash_key' => env('MPU_HASH_KEY', ''),
            'merchant_id' => env('MPU_MERCHANT_ID', ''),
            'frontend_url' => env('MPU_FRONTEND_URL', ''),
            'backend_url' => env('MPU_BACKEND_URL', ''),
            'payment_url' => env('MPU_PAYMENT_URL', ''),
            'charge_type' => env('MPU_CHARGE_TYPE', ''),
            'charge' => env('MPU_CHARGE', ''),
        ],
        'transfer' => [
            'enable' => env('TRANSFER_ENABLE', ''),
            'transfer_1' => env('TRANSFER_1', ''),
            'transfer_2' => env('TRANSFER_2', ''),
            'transfer_3' => env('TRANSFER_3', ''),
            'transfer_4' => env('TRANSFER_4', ''),
            'transfer_5' => env('TRANSFER_5', ''),
            'transfer_6' => env('TRANSFER_6', ''),
            'transfer_7' => env('TRANSFER_7', ''),
            'transfer_8' => env('TRANSFER_8', ''),
            'transfer_9' => env('TRANSFER_9', ''),
            'transfer_10' => env('TRANSFER_10', ''),
            'charge_type' => env('TRANSFER_CHARGE_TYPE', ''),
            'charge' => env('TRANSFER_CHARGE', ''),
        ],
        'onetwothree'   => [
            'enable' => env('ONETWOTHREE_ENABLE', ''),
            'MerchantID' => env('ONETWOTHREE_MERCHANTID', ''),
            'Merchantpassword' => env('ONETWOTHREE_MERCHANTPASSWORD', ''),
            'Version' => env('ONETWOTHREE_VERSION', ''),
            'CurrencyCode' => env('ONETWOTHREE_CURRENCYCODE', ''),
            'CountryCode' => env('ONETWOTHREE_COUNTRYCODE', ''),
            'AgentCode' => env('ONETWOTHREE_AGENTCODE', ''),
            'ChannelCode' => env('ONETWOTHREE_CHANNELCODE', ''),
            'ApiKey' => env('ONETWOTHREE_APIKEY', ''),
            'Url' => env('ONETWOTHREE_URL', ''),
            'charge_type' => env('ONETWOTHREE_CHARGE_TYPE', ''),
            'charge' => env('ONETWOTHREE_CHARGE', ''),
        ],
        'visa_master'   => [
            'enable' => env('VISA_MASTER_ENABLE', ''),
            'version' => env('VISA_MASTER_VERSION', ''),
            'currency' => env('VISA_MASTER_CURRENCY', ''),
            'hash_key' => env('VISA_MASTER_HASH_KEY', ''),
            'merchant_id' => env('VISA_MASTER_MERCHANT_ID', ''),
            'frontend_url' => env('VISA_MASTER_FRONTEND_URL', ''),
            'backend_url' => env('VISA_MASTER_BACKEND_URL', ''),
            'payment_url' => env('VISA_MASTER_PAYMENT_URL', ''),
            'charge_type' => env('VISA_MASTER_CHARGE_TYPE', ''),
            'charge' => env('VISA_MASTER_CHARGE', ''),
        ],
        'mab'   => [
            'enable' => env('MAB_ENABLE', ''),
            'MID' => env('MAB_MID', ''),
            'ShareKey' => env('MAB_SHAREKEY', ''),
            'MName' => env('MAB_MNAME', ''),
            'url' => env('MAB_URL', ''),
            'frontend_url' => env('MAB_FRONTEND_URL', ''),
            'act_url' => env('MAB_ACT_URL', ''),
            'charge_type' => env('MAB_CHARGE_TYPE', ''),
            'charge' => env('MAB_CHARGE', ''),
        ],
        'truemoney'   => [
            'enable' => env('TRUE_ENABLE', ''),
            'hash_key' => env('TRUE_HASH_KEY', ''),
            'merchant_id' => env('TRUE_MERCHANT_ID', ''),
            'url' => env('TRUE_PAYMENT_URL', ''),
            'backend_url' => env('TRUE_BACKEND_URL', ''),
            'charge_type' => env('TRUE_CHARGE_TYPE', ''),
            'charge' => env('TRUE_CHARGE', ''),
        ],
        'deposit'   => [
            'enable' => env('DEPOSITE_ENABLE', ''),
            'charge_type' => env('DEPOSITE_CHARGE_TYPE', ''),
            'charge' => env('DEPOSITE_CHARGE', ''),
            'secret_key' => env('DEPOSITE_SECRET_KEY', ''),
        ],
        'wave'   =>  [
            'enable' => env('WAVE_ENABLE', ''),    
            'public_key'  =>  env('WAVE_PUBLIC_KEY', ''), 
            'private_key' =>  env('WAVE_PRIVATE_KEY', ''),
            'charge_type' => env('WAVE_CHARGE_TYPE', ''),
            'charge' => env('WAVE_CHARGE', ''),
        ],
        'kbzdirect'   => [
            'enable' => env('KBZDIRECTPAY_ENABLE', ''),
            'client_code' => env('KBZDIRECTPAY_CLIENT_CODE', ''),
            'merchant_code' => env('KBZDIRECTPAY_MERCHANT_CODE', ''),
            'currency_code' => env('KBZDIRECTPAY_CURRENCY_CODE', ''),
            'success_flag' => env('KBZDIRECTPAY_SUCCESS_FLAG', ''),
            'fail_flag' => env('KBZDIRECTPAY_FAIL_FLAG', ''),
            'payment_url' => env('KBZDIRECTPAY_PAYMENT_URL', ''),
            'success_url' => env('KBZDIRECTPAY_SUCCESS_URL', ''),
            'failed_url' => env('KBZDIRECTPAY_FAILED_URL', ''),
            'charge_type' => env('KBZDIRECTPAY_CHARGE_TYPE', ''),
            'charge' => env('KBZDIRECTPAY_CHARGE', ''),
        ],
        'cb'   => array(
            'enable' => env('CBPAY_ENABLE', 'true'),
            'remote_enable' => env('CBPAY_REMOTE_ENABLE', 'true'),
            'money_enable' => env('CBPAY_MONEY_ENABLE', 'true'),
            'merchant_key' => env('CBPAY_MERCHANT_KEY', 'BNFEXKEYS'),
            'merchant_id' => env('CBPAY_MERCHANT_ID', 'BNFEX'),
            'currency' => env('CBPAY_CURRENCY', 'MMK'),
            'common_key' => env('CBPAY_COMMON_KEY', 'CBPAYMENT'),
            'payment_url' => env('CBPAY_PAYMENT_URL', "http://online.cbbank.com.mm/CBPayEnc/servletcontroller"),
            'charge_type' => env('CBPAY_CHARGE_TYPE', 'amount'),
            'charge' => env('CBPAY_CHARGE', '100'),
            'encrypt_salt' => env('CBPAY_ENCRYPT_SALT', "rIkZOJxkiNNUQ2AKGG9wiQM="),
            'encrypt_vector' => env('CBPAY_ENCRYPT_VECTOR', "TZuWY0W5Yn9l9F2DEiU0hg=="),
        ),
    ],
    'aes' => [
        'pin'             => env('AES_PIN',''),
        'iv_value'        => env('AES_IV_VALUE',''),
        'key_value'       => env('AES_KEY_VALUE',''),
        'session_name'    => env('AES_SESSION_NAME',''),
    ]
];
